const fs = require('fs');
const htmlToDocx = require('html-to-docx');
const path = require('path');

const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Business Logic - PUP OUS Document Admission & Requirement Monitoring</title>
  <style>
    body { font-family: 'Arial', sans-serif; font-size: 11pt; line-height: 1.5; color: #333333; }
    h1 { color: #800000; font-size: 24pt; border-bottom: 2px solid #800000; padding-bottom: 5px; }
    h2 { color: #800000; font-size: 18pt; margin-top: 20px; }
    h3 { color: #555555; font-size: 14pt; margin-top: 15px; }
    p { margin-bottom: 10px; }
    ul { margin-bottom: 15px; }
    li { margin-bottom: 5px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th, td { border: 1px solid #cccccc; padding: 8px; text-align: left; }
    th { background-color: #f2f2f2; color: #800000; }
  </style>
</head>
<body>
  <h1>Business Logic Specification</h1>
  <p><strong>System Name:</strong> PUP OUS Document Admission & Requirement Monitoring</p>
  <p><strong>Date:</strong> July 2026</p>

  <h2>1. Executive Summary</h2>
  <p>The PUP Open University System (PUP OUS) Document Admission & Requirement Monitoring application is a comprehensive web-based platform designed to track, validate, and manage academic document submissions from prospective and current students. The system centralizes document receipt, identifies deficiencies in requirements, automates student notifications, and provides robust auditing and reporting capabilities for the Admission Office.</p>

  <h2>2. System Roles and Access Control</h2>
  <p>The system utilizes Role-Based Access Control (RBAC) with three primary roles:</p>
  <ul>
    <li><strong>Clerk:</strong> Responsible for frontline data entry. They log incoming document submissions (walk-in or via courier) and can view basic student records.</li>
    <li><strong>Officer:</strong> Responsible for validation and processing. They can verify submitted documents against checklists, mark deficiencies, and approve or reject submissions.</li>
    <li><strong>Admin:</strong> Has full system access. Admins can manage user accounts, customize email templates, configure dynamic document checklists for different admission purposes, and access full audit logs.</li>
  </ul>

  <h2>3. Core Data Entities</h2>
  <h3>3.1 PUPSubmission (Student Submissions)</h3>
  <p>Represents a single instance of a student submitting academic documents. Core fields include:</p>
  <ul>
    <li><strong>Tracking ID:</strong> A unique system-generated identifier (e.g., PUP-OUS-2026-0001).</li>
    <li><strong>Purpose:</strong> The admission type or process (e.g., Admission (Graduate), Admission (Bachelors), Comprehensive Exam, Graduation, Deficiency).</li>
    <li><strong>Student Information:</strong> First Name, Last Name, Email, Contact Number.</li>
    <li><strong>Delivery Method:</strong> How the documents were received (Walk-in, LBC Express, DHL Express, J&T Express, Other Courier). Includes Tracking Number for couriers.</li>
    <li><strong>Documents Checklist:</strong> An array of documents associated with the submission, each marked as 'checked' or 'missing', and 'required' or 'optional'.</li>
    <li><strong>Status/Notified:</strong> Indicates if the student has been officially notified via the automated email system.</li>
  </ul>

  <h3>3.2 SimulatedEmail (Notifications)</h3>
  <p>Logs and tracks the automated emails generated by the system, recording the recipient, exact subject, compiled body (text/html), and timestamp.</p>

  <h3>3.3 AuditLogEntry (Audit Trail)</h3>
  <p>Provides a non-repudiable record of system activities. It captures the User, Role, Action Type (CREATE, UPDATE, DELETE, IMPORT, EXPORT, RESET), target entity ID, timestamp, and specific details of the action.</p>

  <h2>4. Key Workflows and Business Processes</h2>
  <h3>4.1 Document Logging and Receipt</h3>
  <p>When documents arrive physically at the Admission Office, a Clerk or Officer logs the submission into the system. They select the purpose, input student details, and specify the delivery method. Based on the selected 'Purpose', the system dynamically loads the required Document Checklist.</p>

  <h3>4.2 Deficiency Tracking and Validation</h3>
  <p>The Officer reviews the physical documents against the digital checklist. Missing required documents are flagged as "Deficiencies". The system visually differentiates between complete submissions and those pending requirements.</p>

  <h3>4.3 Automated Email Notifications</h3>
  <p>Upon saving a new submission or updating an existing one, the system automatically dispatches an email to the student's provided address. The system uses a customizable plain-text or HTML template (configured by the Admin) and injects dynamic variables (e.g., {studentName}, {trackingId}, {receivedDocuments}, {pendingDocuments}). This ensures instant, standardized communication regarding receipt and missing requirements.</p>

  <h3>4.4 Process Slip Generation</h3>
  <p>The system can generate a printable "Process Slip" for each submission. This slip serves as a physical routing document attached to the student's folder as it moves through internal validation queues.</p>

  <h2>5. System Configuration and Administration</h2>
  <h3>5.1 Dynamic Document Checklists</h3>
  <p>Admins can configure the default checklist items for each 'Purpose'. This ensures the system adapts to changing policy requirements (e.g., adding a new medical certificate requirement for Graduate Admission) without needing code changes.</p>

  <h3>5.2 Email Template Customization</h3>
  <p>Admins can modify the default message sent to students. They can edit the subject line and the main body text, utilizing placeholders to maintain personalization while strictly adhering to the PUP OUS brand guidelines and institutional template frame.</p>

  <h3>5.3 User Management</h3>
  <p>Admins can provision new accounts, assign roles, and revoke access, ensuring only authorized personnel can access sensitive student records.</p>

  <h2>6. Reporting and Auditing</h2>
  <p>The system features a centralized dashboard that displays real-time metrics: Total Submissions, Pending Notifications, Submissions with Deficiencies, and submissions received 'Today'. The extensive Audit Log ensures full accountability, tracking who modified which record and when.</p>

</body>
</html>
`;

(async () => {
  try {
    const buffer = await htmlToDocx(htmlContent, null, {
      table: { row: { cantSplit: true } },
      footer: true,
      pageNumber: true,
    });
    const outputPath = path.join(__dirname, 'public', 'Business_Logic.docx');
    fs.writeFileSync(outputPath, buffer);
    console.log('Successfully created Business_Logic.docx in public folder.');
  } catch (error) {
    console.error('Error generating docx:', error);
  }
})();
